name: quiz
description: A new Flutter project.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fluent_ui: ^4.8.0
  fluentui_system_icons: ^1.1.222
  window_manager: ^0.3.5

  circular_countdown_timer: ^0.2.3
  auto_size_text: ^3.0.0

  provider: ^6.0.5
  file_picker: 5.2.0+1 # 5.3.2 crashes

  uuid: ^3.0.7
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  drift: ^2.19.1

  exif: ^3.1.4

  nsd: ^2.3.1
  grpc: ^3.2.2

  google_maps_flutter: ^2.3.1
  maps_launcher: ^2.2.0

  webview_flutter: ^4.2.2

  lottie: ^2.5.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3

  intl: ^0.18.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.19.0
  build_runner: ^2.4.5

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/lottie/

  fonts:
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: lib/assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
